service: serverless-offline-direct-lambda-example

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-offline
  - serverless-offline-direct-lambda

functions:
  hello:
    handler: handler.hello
